services:
  crm_test:
    image: crm_test
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        BASE_IMAGE: ros:jazzy
    container_name: crm_test
    stop_signal: SIGINT
    network_mode: bridge
    privileged: true
    stdin_open: true
    pid: host
    ipc: host
    tty: true
    user: user
    volumes:
      - ../:/home/user/crm_test_ws/src/
      - ~/.ssh:/home/user/.ssh
      - ~/.gitconfig:${HOME}/.gitconfig:ro
    environment:
      - DISPLAY=:1
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=42
      - ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST
    ports:
      - "6080:6080"
    command: bash -c "
      vncserver :1 -geometry 1280x720 -depth 24 -SecurityTypes None && \
      sleep 5 && \
      /opt/novnc/utils/novnc_proxy --vnc localhost:5901 --listen 6080 & \
      sleep 5 && \
      source /opt/ros/jazzy/setup.bash && \
      ros2 run rviz2 rviz2"