name: CRM Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-jazzy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check if image exists
        id: check_image
        run: |
          if docker pull ghcr.io/${{ github.repository }}/crm_test:jazzy; then
            echo "image_exists=true" >> $GITHUB_OUTPUT
          else
            echo "image_exists=false" >> $GITHUB_OUTPUT
          fi
        continue-on-error: true
      
      - name: Build and push image if it doesn't exist
        if: steps.check_image.outputs.image_exists != 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/crm_test:jazzy
          build-args: |
            BASE_IMAGE=ros:jazzy
      
      - name: Build Packages with Testing Enabled
        run: |
          docker compose -f docker/docker-compose.yaml run build-jazzy
      
      - name: Run Tests
        run: |
          docker compose -f docker/docker-compose.yaml run test-jazzy